# Production environment override
services:
  php:
    build:
      target: php_prod
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      APP_SECRET: ${APP_SECRET}

  caddy:
    build:
      target: caddy_prod
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - caddy_data:/data
      - caddy_config:/config

  db:
    build:
      target: postgres_dev
      context: .
      dockerfile: Dockerfile
