name: CI

on:
  push:
    branches:
      - main
  pull_request: ~
  workflow_dispatch: ~

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    env:
      DOCKER_PHP_TEST_TAG: "$GITHUB_REPOSITORY-php:test"
      DOCKER_PHP_BUILD_TARGET: php_test

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Copy configuration files
        run: |
          cp ./app/.php-cs-fixer.dist.php ./app/.php-cs-fixer.php
          cp ./app/phpstan.dist.neon ./app/phpstan.neon
          cp ./app/phpunit.xml.dist ./app/phpunit.xml

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build PHP test container
        run: docker build -t $DOCKER_PHP_TEST_TAG --target $DOCKER_PHP_BUILD_TARGET -f ./Dockerfile .

      - name: Run PHP CS Fixer
        run: docker run --rm $DOCKER_PHP_TEST_TAG vendor/bin/php-cs-fixer fix --using-cache=no --verbose --diff

      - name: Run PHPStan
        run: docker run --rm $DOCKER_PHP_TEST_TAG vendor/bin/phpstan analyse src

      - name: Run PHPUnit
        run: docker run --rm $DOCKER_PHP_TEST_TAG php vendor/bin/phpunit
